config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  get '/', to: 'root#show', as: 'root'
  get '/dashboard', to: 'users#show', as: 'dashboard'

  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  get '/auth/foursquare/callback', to: 'sessions#create'

  get '/venues/search', to: 'venues#index', as: 'venues'
  get '/venues/:venue_id', to: 'venues#show', as: 'venue'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/foursquare_tip.rb
class FoursquareTip
  attr_reader :created_at,
              :user,
              :description,
              :agree_count,
              :disagree_count,
              :photo

  def initialize(tip_hash)
    @created_at = format_time(tip_hash['createdAt'])
    @user = get_user(tip_hash['user'])
    @description = tip_hash['text']
    @photo = get_photo(tip_hash['user']['photo'])
    @agree_count = tip_hash['agreeCount']
    @disagree_count = tip_hash['disagreeCount']
  end

  def get_user(user_data)
    "#{user_data['firstName']} #{user_data['lastName']}"
  end

  def get_photo(photo_hash)
    "#{photo_hash['prefix']}150x150#{photo_hash['suffix']}"
  end

  def format_time(time_in_seconds)
    Time.at(time_in_seconds).strftime('%m-%d-%Y')
  end
end

app/models/foursquare_user.rb
class FoursquareUser < OpenStruct

  def self.service
    @@service ||= YourSquareDashboardService.new
  end

  def self.find_by(id)
    user_data = service.get_user(id)['response']['user']
    FoursquareUser.new(
      photo: photo_url(user_data['photo']),
      fullname: full_name(user_data['firstName'],
                          user_data['lastName']),
      followers: user_data['followers']['count'],
      following: user_data['following']['count'],
      email: user_data['contact']['email'],
      location: user_data['homeCity']
    )
  end

  def self.full_name(first_name, last_name)
    "#{first_name} #{last_name}"
  end

  def self.photo_url(photo_data)
    photo_data['prefix'] + '200x200' + photo_data['suffix']
  end
end

app/models/foursquare_user_checkin.rb
class FoursquareUserCheckin < OpenStruct
  def self.service
    @@service ||= YourSquareDashboardService.new
  end

  def self.where(user_id_hash)
    fs_response = service.get_user_checkins(user_id_hash[:user])
    unless fs_response['count'] < 1
      fs_response['items'].map do |checkin|
        FoursquareUserCheckin.new(
          venue: checkin['venue']['name'],
          venue_id: checkin['venue']['id']
        )
      end
    end
  end
end

app/models/foursquare_venue.rb
class FoursquareVenue < OpenStruct
  def self.service
    @@service ||= YourSquareVenueService.new
  end

  def self.connection(token)
    service.instantiate_token(token)
  end

  def self.find(id)
    venue_response = service.get_venue(id)
    FoursquareVenue.new(
      name: venue_response['name'],
      address: venue_response['location']['address'],
      categories: get_categories(venue_response['categories']),
      hours: venue_hours(id),
      tips: get_tips(id)
    )
  end

  def self.venue_hours(id)
    service.get_venue_hours(id)['hours']['timeframes']
  end

  def self.venue_tips(id)
    service.get_venue_tips(id)['tips']['items']
  end

  def self.get_categories(categories)
    categories.map do |cat|
      cat['name']
    end
  end

  def self.get_tips(id)
    venue_tips(id).map do |tip|
      FoursquareTip.new(tip)
    end.sort_by{ |t| t.agree_count }.reverse
  end

  def self.photo(id)
    raw_photo = service.get_venue_photos(id)['response']['photos']['items'][0]
    "#{raw_photo['prefix']}300x300#{raw_photo['suffix']}"
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :uid, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :username

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(uid: session[:user_id])
    end
  end

  def username
    @username ||= FoursquareUser.find_by(current_user.uid).fullname
  end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    response_data = request.env["omniauth.auth"]
    token = OauthTokenReceiver.new.exchange_code_for_token(params[:code])
    user = YourSquareUserService.new.instantiate_user(response_data.uid, token)
    if user
      session[:user_id] = user.uid
    end
    redirect_to dashboard_path
  end

  def destroy
    session.clear
    flash[:success] = 'Come back soon!'
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = FoursquareUser.find_by(current_user.uid)
    @user_checkins = FoursquareUserCheckin.where(user: current_user.uid)
  end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  def index
    @venues = VenueLocator.new(current_user, params[:search]).fetch_venues
  end

  def show
    FoursquareVenue.connection(current_user.token)
    @venue = FoursquareVenue.find(params[:venue_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def query
    params['search']['venue']
  end
end

app/views/layouts/_browse_nav.html.haml
.nav-bar-browse
  %ul.dropdown.menu.align-right{ 'data-dropdown-menu' => ''}
    - if current_user
      %li.user-info
        %a
          %i{class: 'fi-torso'}
          = username
          %ul.menu
            %li
              = link_to 'Dashboard', dashboard_path
            %li
              = link_to 'Logout', logout_path, method: 'delete'
    - else
      %li.user-info
        %a Login
        %ul.menu
          %li
            %a{ href: "https://foursquare.com/oauth2/authenticate?client_id=#{ENV['foursquare_id']}&response_type=code&redirect_uri=http://localhost:3000/auth/foursquare/callback" }
              %i.fi-social-foursquare.medium
              Login

    %ul.menu
      %li
        = link_to 'YourSquare', root_path, class: 'menu-text'
      %li
        %input{ type: 'text', placeholder: "I'm looking for..."}
      %li
        %input{ type: 'text', placeholder: "Location", class: 'nav-location'}

app/views/layouts/_default_nav.html.haml
.nav-bar-primary
  .row
    .small-12.columns
      %ul.dropdown.menu.align-right{ 'data-dropdown-menu' => ''}
        - if current_user
          %li.user-info
            %a
              %i{class: 'fi-torso'}
              = username
              %ul.menu
                %li
                  = link_to 'Dashboard', dashboard_path
                %li
                  = link_to 'Logout', logout_path, method: 'delete'
        - else
          %li.user-info
            %a Login
            %ul.menu
              %li
                %a{ href: "https://foursquare.com/oauth2/authenticate?client_id=#{ENV['foursquare_id']}&response_type=code&redirect_uri=http://localhost:3000/auth/foursquare/callback" }
                  %i.fi-social-foursquare.medium
                  Login


        %ul.menu
          %li
            = link_to 'YourSquare', root_path, class: 'menu-text'

app/views/layouts/application.html.haml
!!!
%html{ :lang => "en" }
  %head
    %meta{ :charset => "utf-8" }

    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }

    %title= content_for?(:title) ? yield(:title) : "Your Square"

    %link{ rel: "stylesheet", href: "https://cdn.jsdelivr.net/foundation-icons/3.0/foundation-icons.min.css" }
    %link{ href: "https://fonts.googleapis.com/css?family=Raleway", rel: "stylesheet" }
    = stylesheet_link_tag "application"
    = stylesheet_link_tag "custom"
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tag

  %body
    - if params[:controller] == 'root'
      = render partial: 'layouts/default_nav'
    - else
      = render partial: 'layouts/browse_nav'


    - flash.each do |type, message|
      = content_tag( :div, sanitize(message), class: "flash-#{type}" )

    = yield

app/views/root/show.html.haml
.root-background
%div
  .filler
  .row.root-container
    %form{ method: 'get', action: '/venues/search' }
      .small-3.small-offset-3.columns
        %input{ type: 'text', placeholder: "I'm looking for...", name: 'search[venue]' }
      .small-2.columns
        %select
          %option{ name: "search[location]" }Location1
          %option{ name: "search[location]" }Location2
      .small-2.end.columns.search-btn-container
        %button{ class: 'success button', type: 'submit' }
          %i.fi-map
          Search

app/views/users/show.html.haml
.dashboard-background
.dashboard-filler
%div#account-information
  .row.info-container
    .small-3.columns
      = image_tag @user.photo, class: 'user-avatar'
    .small-3.columns#account-details
      %h3= @user.fullname
      %p= @user.email
    .small-5.columns#account-stat-container
      .dashboard-filler
      .row
        %ul#social-stats
          .small-3.columns
            %li
              %h5 0
              .stat
                %i.fi-lightbulb.medium
              %p.outer-text Ideas
          .small-3.columns
            %li
              %h5= @user.followers
              .stat
                %i.fi-torsos-all.medium
              %p.inner-text Followers
          .small-3.columns
            %li
              %h5= @user.following
              .stat
                %i.fi-torsos-all.medium
              %p.inner-text Following
          .small-3.columns
            %li
              %h5 0
              .stat
                %i.fi-list-bullet.medium
              %p.outer-text Lists
.row#user-favorites
  %h4
    = @user.fullname
    \'s Recent Checkins
  - @user_checkins.each do |checkin|
    .small-4.columns.recent-lists.callout.end
      .top-list
      -# .top-list{ style: "background-image: url('#{checkin.photo}')" }
      %hr
      .bottom-list
        %h5
          = link_to checkin.venue, venue_path(checkin.venue_id)

app/views/venues/index.html.haml
.dashboard-filler
%h5 Results for #{query}

app/views/venues/show.html.haml
%div
  .dashboard-filler
  .row.venue-container
    %h3#venue-header= @venue.name
    .small-3.columns.callout.primary
      %ul#venue-details
        %li 
          Address: 
          %strong
            #{@venue.address}
        %li 
          Categories:
          %ul
            - @venue.categories.each do |category|
              %li
                %strong
                  = category
    .small-8.tips-container.columns.small-offset-1.end
      %h5#tips-header Tips from this location:
      - @venue.tips.each do |tip|
        .row
          .small-3.columns.thumbnail-container
            %img{ src: "#{tip.photo}", class: 'tip-photo' }
          .small-4.columns.tip-container
            %ul.tip-details
              %li 
                %strong
                  Date Posted: 
                #{tip.created_at}

              %li 
                %strong
                  User: 
                #{tip.user}

              %li 
                %strong
                  Agree: 
                #{tip.agree_count}

              %li 
                %strong
                  Disagree: 
                #{tip.disagree_count}

          .small-4.columns
            %p= tip.description
        %hr